#
# REF:
#   1. https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategymatrixinclude
#
name: Test Creating Release Draft

on:
  push:
    branches:
    - release/freebsd
    tags:
    - 'v*'

defaults:
  run:
    shell: bash

jobs:
  standard:
    name: Std

    strategy:
      fail-fast: false
      matrix:
        target:
        - aarch64-unknown-linux-musl
        extra: ['bin']
        include:
        - target: aarch64-unknown-linux-musl
          os: ubuntu-22.04

    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v4

    - name: Update Rust Toolchain Target
      run: |
        echo "targets = ['${{matrix.target}}']" >> rust-toolchain.toml

    - name: Setup Rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1.9.0
      # WARN: Keep the rustflags to prevent from the winget submission error: `CAQuietExec: Error 0xc0000135`
      with:
        cache: false
        rustflags: ''

    - name: Setup Nushell
      uses: hustcer/setup-nu@v3.13
      with:
        version: 0.98.0

    - name: Release Nu Binary
      id: nu
      run: |
        docker pull messense/rust-musl-cross:aarch64-musl
        docker run --rm -v "$(pwd)":/home/rust/src messense/rust-musl-cross:aarch64-musl cargo build --release --all --features=static-link-openssl

